### ISSUE TITLE
returns en dash (–) ?

### ISSUE THREAD

**Issue by nuckdae** [pbakondy/mcc-mnc-list#19]
Hello.
Your code is very helpful.
Thank you for developing and maintaining.

When I've downloaded your source and run the following command, mcc-mnc-list.json is updated.
```
node fetch.js
```
But countryName and countryCode are null.
The reason seems like the WIKI page has en dash (–) but your code checks hyphen(-).
https://github.com/PodgroupConnectivity/mcc-mnc-list/blob/master/fetch.js#L55 returns en dash (–)

Is this expected? Or did I've done something wrong?

Thank you in advance.

Regards,
Jun

**Comment by pbakondy** [comment]
@nuckdae 
"countryName and countryCode are null" - where?
I ran fetch script again and I saw no issues

**Comment by nuckdae** [comment]
@pbakondy 
Thank you for checking.

#### The return value is False in https://github.com/PodgroupConnectivity/mcc-mnc-list/blob/master/fetch.js#L75
> if (sectionName.indexOf(' - ') !== -1) {

Since sectionName  not contains hyphen(-) but contains en dash (–).


#### I could solve temporarily by changing code to below as a workaround.
```
sectionName = node.querySelector('.mw-headline').textContent.replace(/\u2013|\u2014/g, '-').trim();
```
https://github.com/PodgroupConnectivity/mcc-mnc-list/blob/master/fetch.js#L55%C2%A0returns
